# Generated by Django 5.1.1 on 2024-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usercoinmodel_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoinmodel',
            name='coins',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Coins'),
        ),
    ]
