# Generated by Django 5.1.1 on 2024-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usercoinmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinmodel',
            name='has_claimed_reward',
            field=models.BooleanField(default=False, verbose_name='Claimed'),
        ),
    ]
