# Generated by Django 5.1.1 on 2024-10-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardupgrade',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AddField(
            model_name='cardupgrade',
            name='card_icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon'),
        ),
    ]
