# Generated by Django 5.1.1 on 2024-10-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0004_rename_card_description_cardupgrade_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardupgrade',
            old_name='description',
            new_name='card_description',
        ),
        migrations.RenameField(
            model_name='cardupgrade',
            old_name='icon',
            new_name='card_icon',
        ),
        migrations.RenameField(
            model_name='cardupgrade',
            old_name='level',
            new_name='card_level',
        ),
        migrations.RenameField(
            model_name='cardupgrade',
            old_name='name',
            new_name='card_name',
        ),
        migrations.RenameField(
            model_name='cardupgrade',
            old_name='upgrade_cost',
            new_name='card_upgrade_cost',
        ),
    ]
