# Generated by Django 5.1.1 on 2024-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0006_card_initial_upgrade_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('advanced', 'Advanced'), ('business', 'Business'), ('legendary', 'Legendary')], max_length=10, null=True, verbose_name='Type'),
        ),
    ]
